# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=2000)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
